portafolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from proyectos.views import index

urlpatterns = [
    path("",index,name="index"),
    path('admin/', admin.site.urls),
    path("proyectos/",include("proyectos.urls")),
]


urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

proyectos/urls.py
from django.urls import path
from proyectos.views import Home,RegistrarProyecto,RegistrarUsuario,cerrar_session,iniciar_sesion

app_name = 'proyectos'

urlpatterns = [
    #path("",index, name="index"),
    path("home/",Home.as_view(), name="home"),
    path('registrarUsuario/',RegistrarUsuario.as_view(), name='registrarUsuario'),
    path("formularioProyecto",RegistrarProyecto.formularioProyecto,name="formularioProyecto"),
    path("guardarProyecto",RegistrarProyecto.guardarProyecto,name="guardarProyecto"),
    path("cerrar_sesion/",cerrar_session, name="cerrar_session"),
    path("iniciar_sesion/",iniciar_sesion, name="iniciar_sesion"),

]

proyectos/models.py
from django.db import models
from django.db.models.fields import CharField, URLField
from django.db.models.fields.files import ImageField

class Proyecto (models.Model):
    titulo          = CharField(max_length=100)
    descripcion     = CharField(max_length=250)
    imagen          = ImageField(upload_to="proyectos/imagenes/",null=True)
    url             = URLField(blank=True)
    tipo_proyecto   = CharField(max_length=50,default="")

proyectos/forms.py
from django import forms
    
class FormRegistrarProyecto(forms.Form):
    
    titulo          = forms.CharField(widget=forms.TextInput(
                        attrs={
                            "class": "form-control",
                            "placeholder":"Nombre del proyecto",
                            }))             
    descripcion     = forms.CharField(widget=forms.TextInput(
                        attrs={
                            "class": "form-control",
                            "placeholder":"Descripcion",
                            }))

    imagen          = forms.ImageField()

    url             = forms.URLField(widget=forms.TextInput(
                        attrs={
                            "class": "form-control",
                            "placeholder":"Colocar la URL",
                            }))
    
    tipo_proyecto   = forms.CharField(widget=forms.TextInput(
                        attrs={
                            "class": "form-control",
                            "placeholder":"Escribir solo una opcion: python, php, html, js",
                            }))

proyectos/views.py
from django.shortcuts import render,redirect
from django.views.generic import ListView,View
from django.http import HttpRequest
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth import login,logout,authenticate
from django.contrib import messages

from .models import Proyecto
from .forms import FormRegistrarProyecto

def index(request):
    return render(request,"index.html",None)

class Home(ListView):
    model = Proyecto
    template_name = "home.html"
    context_object_name = 'proyecto'

class RegistrarProyecto(HttpRequest):

    def formularioProyecto(request):
        forms = FormRegistrarProyecto()
        return render(request,"registrarProyecto.html",{"form":forms})
    
    def guardarProyecto(request):
        if request.method == "POST":
            formProyecto = FormRegistrarProyecto(request.POST,request.FILES)
            proyecto = Proyecto()
            if formProyecto.is_valid():
                proyecto.titulo         =request.POST.get("titulo")
                proyecto.descripcion    =request.POST.get("descripcion")
                proyecto.imagen         =request.FILES.get("imagen")
                proyecto.url            =request.POST.get("url")   
                proyecto.tipo_proyecto  =request.POST.get("tipo_proyecto")
                proyecto.save()
                forms = FormRegistrarProyecto()
                return render(request,"registrarProyecto.html",{"mensaje":"OK","form":forms})
            else:
                print("El formulario no es valido")
            
class RegistrarUsuario(View):

    def get(self,request):
        form = UserCreationForm()
        return render(request,"registrar.html",{"form":form})

    def post(self,request):
        form=UserCreationForm(request.POST)
        print(form.errors)
        print(form.is_valid())

        if form.is_valid():

            usuario = form.save()

            login(request, usuario)

        return redirect("proyectos:home")
        #return render(request,"home.html",{})

def cerrar_session(request):
    logout(request)
    return redirect("proyectos:home")
    

def iniciar_sesion(request):
    if request.method=="POST":
        form1=AuthenticationForm(request,data=request.POST)
        
        if form1.is_valid():
            usuario=form1.cleaned_data.get("username")
            clave=form1.cleaned_data.get("password")

            user = authenticate(username=usuario,password=clave)

            if user is not None:
                login(request,user)
                return redirect("proyectos:home")
            else:
                messages.error(request,"Usuario no registrado.")
        else:
            messages.error(request,"Informacion incorrecta.")

    form=AuthenticationForm()
    return render(request,"login.html",{"form":form})

templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
  <!-- Basic -->
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
  <!-- Mobile Metas -->
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <!-- Site Metas -->
  <meta name="keywords" content=""/>
  <meta name="description" content=""/>
  <meta name="author" content="" />
  <!-- <link rel="shortcut icon" href="{% static 'images/favicon.png' %}" type=""> -->

  <title>Unidad 4</title>

  <!-- bootstrap core css -->
  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}" />

  <!--owl slider stylesheet -->
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css" />
  <!-- nice select  -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-nice-select/1.1.0/css/nice-select.min.css" integrity="sha512-CruCP+TD3yXzlvvijET8wV5WxxEh5H8P4cmz0RFbKK6FlZ2sYl3AEsKlLPHbniXKSrDdFewhbmBK5skbdsASbQ==" crossorigin="anonymous" />
  <!-- font awesome style -->
  <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet" />

  <!-- Custom styles for this template -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet" />
  <!-- responsive style -->
  <link href="{% static 'css/responsive.css' %}" rel="stylesheet" />
  <link href="{% static 'css/estilos.css' %}" rel="stylesheet" />

</head>

<body>
  <header class="header_section">
    <div class="container">
      <nav class="navbar navbar-expand-lg custom_nav-container ">
        <a class="navbar-brand" href="index.html">
          <span>
            Unidad 4
          </span>
        </a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class=""> </span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav  ms-auto ">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'proyectos:home' %}">INICIO</a>
            </li>
            {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'proyectos:formularioProyecto' %}">REGISTRAR PROYECTO</a>
              </li>
              <div class="sesiones">
                <li class="nav-item">
                  <a class="nav-link Username" href="{% url 'proyectos:home' %}">{{ user.username }}</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link Username" href="{% url 'proyectos:cerrar_session' %}">SALIR</a>
                </li>
              </div>
            {% else %}
              <div class="sesiones1">
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'proyectos:iniciar_sesion' %}">INICIAR SESION</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'proyectos:registrarUsuario' %}">REGISTRATE</a>
                </li>
              </div>
            {%endif%}
          </ul>
        </div>
      </nav>
    </div>
  </header>

  {% block content %}

  {% endblock content %}  

  

  <!-- footer section -->
  <footer class="footer_section">
    <div class="container">
      <div class="row">
        <div class="col-md-4 footer-col">
          <div class="footer_contact">
            <h4> Contactame</h4>
            <div class="contact_link_box">
              <a href="#">
                <i class="fa fa-map-marker" aria-hidden="true"></i>
                <span>Lima, Villa El Salvador</span>
              </a>
              <a href="#">
                <i class="fa fa-phone" aria-hidden="true"></i>
                <span>+51 941585296</span>
              </a>
              <a href="#">
                <i class="fa fa-envelope" aria-hidden="true"></i>
                <span>taipe.marvin17@gmail.com</span>
              </a>
            </div>
          </div>
        </div>

        <div class="col-md-4 footer-col">
          <div class="footer_detail">
            <a href="#" class="footer-logo">Mis proyectos</a>
            <p>Todos los proyectos que se encuentran en mi portafolio son a base de, HTML, CSS, Bootstrap, Python, PHP, Base de Datos, etc. </p>
          </div>
        </div>

        <div class="col-md-4 footer-col">
          <h4>
            Redes sociales
          </h4>
          <div class="footer_social">
              <a href="http://www.facebook.com">
                <i class="fa fa-facebook" aria-hidden="true"></i>
              </a>
              <a href="http://www.twitter.com">
                <i class="fa fa-twitter" aria-hidden="true"></i>
              </a>
              <a href="http://www.linkedin.com">
                <i class="fa fa-linkedin" aria-hidden="true"></i>
              </a>
              <a href="http://www.instagram.com">
                <i class="fa fa-instagram" aria-hidden="true"></i>
              </a>
            </div>
        </div>
      </div>

      <div class="footer-info">
        <p>&copy;<span id="displayYear"></span> Todos los derechos reservados por
          <a href="">Marvin Taipe Gongora</a><br>
        </p>
      </div>

    </div>
  </footer>
  <!-- footer section -->

  <!-- jQery -->
  <script src="{%  static 'js/jquery-3.4.1.min.js' %}"></script>
  <!-- popper js -->
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
  </script>
  <!-- bootstrap js -->
  <script src="{%  static 'js/bootstrap.js' %}"></script>
  <!-- owl slider -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js">
  </script>
  <!-- isotope js -->
  <script src="https://unpkg.com/isotope-layout@3.0.4/dist/isotope.pkgd.min.js"></script>
  <!-- nice select -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-nice-select/1.1.0/js/jquery.nice-select.min.js"></script>
  <!-- custom js -->
  <script src="{%  static 'js/custom.js' %}"></script>
  

</body>

</html>

templates/home.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

    <div class="hero_area">
        <div class="bg-box">
        <img src="{% static 'images/banner_inicio2.jpg' %}" alt="">
        </div>

        <section class="slider_section d-flex flex-column justify-content-end">
            <div class="container">
                <div class="row">
                    <div class="col-md-7 col-lg-8">
                        <div class="detail-box ">
                            <h1>Marvin Taipe Gongora</h1>
                            <p>Hola que tal, este es mi portafolio del proyecto final de la Unidad 4.</p>
                            <p>Es proyecto esta a base de DJANGO y Base de datos (SQL), además de contenedor los demas tecnologías por default, como HTML5, CSS y BOOTSTRAP.</p>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>

    <section class="food_section layout_padding-bottom">
        <div class="container">
            <div class="heading_container heading_center">
                <h2>MIS PROYECTOS</h2>
            </div>

            <ul class="filters_menu">
                <li class="active" data-filter="*">All</li>
                <li data-filter=".html">HTML</li>
                <li data-filter=".js">JS</li>
                <li data-filter=".python">PYTHON</li>
                <li data-filter=".php">PHP</li>
            </ul>

            <div class="filters-content">
                <div class="row grid">
                    {% for proyect in proyecto %}
                        <div class="col-sm-6 col-lg-4 all {{proyect.tipo_proyecto}}">
                            <div class="box">
                                <div>
                                    <div class="img-box">
                                        <img src="{{proyect.imagen.url}}" alt="{{ proyect.titulo }}">
                                    </div>
                                    <div class="detail-box lista_proyectos">
                                        <h5> {{ proyect.titulo }}</h5>
                                        <p>{{ proyect.descripcion }}</p>
                                    <div class="options">
                                        <a href="{{proyect.url}}" target="_blank">Link del: {{ proyect.titulo }}</a>
                                    </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %} 
                </div>
            </div>
        </div>
    </section>
{% endblock content %}  

templates/index.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

    <section class="book_section layout_padding">
        <div class="container d-flex flex-column align-items-center">
            <div class="heading_container">
                <h2>Bienvenido a mi proyecto de Django</h2>
            </div>
            <div class="row form_proyecto d-flex flex-column align-content-center">
                <div class="col-md-12">
                    <a href="{% url 'proyectos:home' %}" type="boton"> IR AL PROYECTO</a>
                </div>
            </div>
        </div>
    </section>

{% endblock content %}  

templates/login.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

    <section class="book_section layout_padding">
        <div class="container d-flex flex-column align-items-center">
            {% if messages %}
                {% for mensaje in messages %}
                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                        <strong>{{mensaje}}</strong> 
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                {% endfor %}
            {% endif %}
            <div class="heading_container">
                <h2>Iniciar Sesion</h2>
            </div>
            <div class="row form_proyecto d-flex flex-column align-content-center">
                <div class="col-md-12">
                    <div class="form_container">
                        <form action="" method="post" class="d-flex flex-column justify-content-center">
                            {% csrf_token %} 

                            {{ form }}

                            <button type="submit">IniciarSesion</button>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock content %}  

templates/registrar.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

    <section class="book_section layout_padding">
        <div class="container d-flex flex-column align-items-center">
            <div class="heading_container">
                <h2>Registrarse</h2>
            </div>
            <div class="row form_proyecto d-flex flex-column align-content-center">
                <div class="col-md-10">
                    <div class="form_container">
                        <form action="" method="post" class="d-flex flex-column justify-content-center">
                            {% csrf_token %} 

                            {{ form }}

                            <button type="submit">Registrate</button>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock content %}  

templates/registrarProyecto.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

    {% if form.errors %}
    <div class="alert alert-danger" role="alert">
        Error en los campos del formulario
      </div>
    {% endif %}

    <section class="book_section layout_padding">
        <div class="container d-flex flex-column align-items-center">
            {% if mensaje%}
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    <strong>Proyecto registrado correctamente! Click en "Inicio" del menu</strong> 
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% endif %}
            <div class="heading_container">
                <h2>Registrar Proyecto</h2>
            </div>
            <div class="row form_proyecto">
                <div class="col-md-12">
                    <div class="form_container">
                        <form action="{% url 'proyectos:guardarProyecto' %}" method="post" class="d-flex flex-column justify-content-start" enctype="multipart/form-data">
                            {% csrf_token %} 
                            
                            {{ form }}

                            <button type="submit">Guardar</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
      </section>
        
    
{% endblock content %}
    